#!/usr/bin/env perl

use warnings;
use strict;
use autodie qw(:all);

use Geo::Coder::Free;

die "Usage: $0 gedcom-file" unless($ARGV[0]);
die 'Set OPENADDR_HOME to enable testing' unless($ENV{'OPENADDR_HOME'});

# my $g = Geo::Coder::Free::OpenAddresses->new(openaddr => $ENV{'OPENADDR_HOME'});
my $g = Geo::Coder::Free->new(openaddr => $ENV{'OPENADDR_HOME'});

open(my $fin, '-|', "./gedcom -T \"$ARGV[0]\"") or die;

while(my $line = <$fin>) {
	next if($line =~ /\d%/);

	$line =~ s/:\s.+$//;
	$line =~ s/[\r\n]//;

	run($line);
}

sub run {
	my $l = shift;

	# return unless($l =~ /(Canada|US|USA|United States)$/i);

	eval {
		if(!defined($g->geocode($l))) {
			print "$l failed\n";
		}
		# if(my $rc = $g->geocode($l)) {
			# print "$l: ", $rc->{'latitude'}, '/', $rc->{'longitude'}, "\n";
		# }
	};
	if($@) {
		print "$l: $@";
	}
}
