---
# see https://github.com/FGasper/perl-github-action-tips

name: Test Code on BSD
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            version: '13.0'
            pkginstall: pkg install -y p5-LWP-UserAgent-Cached p5-CHI p5-autodie p5-Date-Manip p5-Data-ICal p5-Data-Section p5-Sort-Key-DateTime p5-GIS-Distance p5-Marpa p5-Lingua-EN-Numbers-Ordinate
          - name: openbsd
            version: '7.1'
            pkginstall: pkg_add p5-CHI

    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            sudo hostname example.com
            sudo ${{ matrix.os.pkginstall }}
            yes | sudo cpan -i App::cpanminus
            sudo cpanm -iqn --skip-satisfied Array::Iterator Data::Section::Simple Date::Manip FindBin Gedcom Genealogy::Gedcom::Date Date::Parse IPC::System::Simple CHI File::HomeDir String::Compare HTML::Entities Lingua::Conjunction Lingua::EN::NameCase Lingua::EN::NameParse Lingua::EN::ABC Lingua::String Lingua::EN::Inflect DateTime::Format::Natural Locale::AU Locale::CA Locale::US Data::Text DateTime::Format::Genealogy Parse::RecDescent Sort::Key::DateTime Text::Names::GB Class::Simple::Cached Class::Simple::Readonly::Cached File::Spec Net::OAuth Getopt::Std File::Basename Locale::Object::Country Term::ANSIColor Geo::Coder::Abbreviations Roman Unicode::Diacritic::Strip utf8::all Marpa::R2 B::Lint < /dev/null warnings::unused
            sudo chown -R runner:runner .
            perl -MO=Lint ./gedcom
            perl -c -Mwarnings::unused ./gedcom
